GET http://localhost:3001/api/blogs
###
GET http://localhost:3001/api/blogs/63bc37237c8533cf7f17ffb1
###
DELETE  http://localhost:3001/api/blogs/63bef7be50e3d40979ffea4b
###
POST http://localhost:3001/api/blogs
Content-Type: application/json

{
  "title": "My blog",
  "author": "Clark Kent",
  "url": "www.myblog.com",
  "likes": 15
}
###
PUT http://localhost:3001/api/blogs/63befabe43e7e5d18a0a60b5
Content-Type: application/json

{
  "title": "My blog",
  "author": "Clark Kent",
  "url": "www.myblog.com",
  "likes": 77
}