GET http://localhost:3001/api/users
###
POST http://localhost:3001/api/users
Content-Type: application/json

{
	"username": "tuser",
	"name": "Test User",
	"password": "password"
}
###
POST http://localhost:3001/api/users
Content-Type: application/json

{
	"username": "seconduser",
	"name": "Second User",
	"password": "password"
}