version: '3.8'

services:
  mongo:
    image: mongo
    ports:
      - 3456:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: the_database
    volumes: 
      - ./backend/mongo/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
      - mongo_data:/data/db
  server:
    image: bloglist-backend
    build:
      context: ./backend/
      dockerfile: Dockerfile
    ports:
      - 3001:3000
    volumes:
      - ./backend/:/usr/src/app
    environment: 
      - PORT=3000
      - NODE_ENV=production
      - SECRET=salaisuus
      - MONGODB_URI=mongodb://the_username:the_password@mongo:27017/the_database
    depends_on:
      - mongo
  app:
    image: bloglist-frontend
    build:
      context: ./frontend/
      dockerfile: Dockerfile
    volumes:
      - ./frontend/:/usr/src/app
  nginx:
    image: nginx:1.20.1
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8080:80
    container_name: reverse-proxy
    depends_on:
      - server
      - app

volumes:
 mongo_data: