version: '3.8'

services:
  mongo:
    image: mongo
    ports:
      - 3456:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: the_database
    volumes: 
      - ./mongo/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
      - mongo_data:/data/db
  server:
    image: bloglist-backend-dev
    build:
      context: .
      dockerfile: dev.Dockerfile
    volumes:
      - ./:/usr/src/app
    ports:
      - 3001:3001
    environment:
      - PORT=3001
      - NODE_ENV=development
      - SECRET=salaisuus
      - MONGODB_URI=mongodb://the_username:the_password@mongo:27017/the_database
    depends_on:
      - mongo

volumes:
  mongo_data: